### ISSUE TITLE
Find data on number smartphone usage in Campinas

### ISSUE THREAD

**Issue by antonmc** [antonmc/ima#18] opened 2017-08-11 13:56 UTC

**Comment by dpf2000** [comment] 2017-08-11 14:29
The first statistics I found came from ANATEL and can be accessed in this link:

https://cloud.anatel.gov.br/index.php/s/TpaFAwSw7RPfBa8

ANATEL: Regulating body of the Brazilian federal government responsible for the control and regulation of everything that says respect to telecommunications in the country

**Comment by dpf2000** [comment] 2017-08-11 17:20
I creat another document where I plot all data providev by ANATEL related to local code 19 (used in Campinas and another town in the metropolitan area). So this numbers are no specific about Campinas. The link is https://docs.google.com/spreadsheets/d/1j28SrOrXQrxeajWbivM779SJY_VX8ci7_RrIh_NoQTM/edit?usp=sharing

**Comment by dpf2000** [comment] 2017-08-11 17:22
I don't know what the number "access" means. Anatel did not provide an explanation of this in its documentation. These numbers were passed by all the telephone companies and the chart is related to the consolidated value from month to month since the year 2015.

**Comment by dpf2000** [comment] 2017-08-11 18:12
I spent about 1 hour looking for research on the number of smartphones in use in Campinas and could not find anything. What I found were paid surveys of smartphone sales nationwide. I did not have access to them, obviously. One is from IDG and another is from FGV (Faculdade Getúlio Vargas). Monday I'll try to get something else.

**Comment by VictorFloren** [comment] 2017-08-12 13:20
Guys, I did not found any number specifically, but there is this event called "Connected Smart Cities" (http://www.connectedsmartcities.com.br/?lang=en)  - sadly the next date will be in 4th and 5th of September - and it's related with the Urban System (http://www.urbansystems.com.br/urban-media/tags/Campinas) specialised in market intelligence... 

But the thing is is that they released some information about Campinas being the 2nd most intelligent city in the state of São Paulo. They use all these indicators: Mobility, Urbanism, Technology and Innovation, Entrepreneurship, Governance, Education, Energy, Environment, Health, Safety and Economy.

Could we use this kind of information to say that we're working on a region of potential growth and, therefore, the use of Smartphone in Campinas becomes more natural? Btw, I am attaching a file in which the informations I've took from this site: 
- http://ci.eco.br/connected-smart-cities-2017-anuncia-ranking-de-cidades-inteligentes/
- http://correio.rac.com.br/mobile/materia_historico.php?id=483655


![campinas is the 2nd most intelligent city](https://user-images.githubusercontent.com/30841097/29241013-73e8c4c0-7f47-11e7-979d-87134caab34e.png)

**Comment by dpf2000** [comment] 2017-08-14 12:45
I had a chat with the people in the telecom area, they pointed me to a website where I was able to find updated statistics. This statistic is of national scope, therefore, I will be extrapolating the numbers to Campinas. This is the site: http://www.teleco.com.br/ncel.asp

Currently the index is 116.65 cell phones per 100 inhabitants in Brazil (1,1665 cell phones per person).

Considering that Campinas has 1,200,000 inhabitants, this would mean an estimated total of 1,399,800 cell phones in the city.

Does this estimated number, based on the national average, meet your needs? Or do they suggest any additional study?

**Comment by dpf2000** [comment] 2017-08-14 13:09
Considering the statistical data that I had obtained from Anatel (in the spreadsheet whose link I mentioned above) and these data from Telecon's website, I observe a downward trend in the concentration of cell phones, which is confirmed by the decrease in the number of accesses via mobile devices that The Anatel reports.

You can see that in June 2016 the cellular concentration was 123.03 per 100 inhabitants and now in June 2017 it is 116.65 with constant falls every four months.

I can not confirm this, but I imagine that this is due to the economic crisis that our country is experiencing.

**Closed as completed** 2017-08-14 14:41 UTC
